### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ksyao2002** [renproject/ren-substrate#1]
Is there any documentation on what this substrate pallet aims to do or accomplish? Is it meant to implement darknodes, or the mpc, etc?

**Comment by 0x31** [comment]
It implemented ren tokens (e.g. renBTC) and their corresponding on-chain minting and burning logic, so that assets could be bridged to participating parachains. This repo is a few years old - we are currently targeting parachains with EVM support instead.

This was equivalent to the `gateway-sol` repo for EVM chains and `ren-solana` for Solana.
